server:
  port: 8085
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://172.17.160.1:8082/realms/webshop
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/webshop
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            scope:
              - metrics
            client-id: admin-service
            client-secret: eeNZ5418ETcyGWJztTOlkvVYkBFShYYR
          login:
            provider: keycloak
            scope:
              - metrics
              - openid
            client-id: admin-service
            client-secret: eeNZ5418ETcyGWJztTOlkvVYkBFShYYR
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus