spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.0.106:8082/realms/webshop
      client:
        provider:
          keycloak:
            issuer-uri: http://192.168.0.106:8082/realms/webshop
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            scope:
              - metrics
            client-id: admin-service
            client-secret: eeNZ5418ETcyGWJztTOlkvVYkBFShYYR
          login:
            provider: keycloak
            scope:
              - metrics
              - openid
            client-id: admin-service
            client-secret: eeNZ5418ETcyGWJztTOlkvVYkBFShYYR
          discovery:
            provider: keycloak
            client-id: admin-service
            client-secret: eeNZ5418ETcyGWJztTOlkvVYkBFShYYR
            authorization-grant-type: client_credentials
            scope:
              - discovery
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.106:8761/eureka/
    register-with-eureka: false
  instance:
    prefer-ip-address: true