spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/feedback
  boot:
    admin:
      client:
        enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/webshop
      client:
        registration:
          keycloak:
            client-id: feedback-service-metrics-client
            client-secret: jlj3mUxbKuGvSW2VSXe67NcguLmURTg3
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
          discovery:
            provider: keycloak
            client-id: feedback-service-metrics-client
            client-secret: jlj3mUxbKuGvSW2VSXe67NcguLmURTg3
            authorization-grant-type: client_credentials
            scope:
              - discovery
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/webshop
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true