scrape_configs:
  - job_name: webshop_admin_service
    static_configs:
      - targets: ["http://192.168.0.106:8085"]
    metrics_path: /actuator/prometheus

  - job_name: webshop_catalogue_service
    static_configs:
      - targets: ["http://192.168.0.106:8181"]
    metrics_path: /actuator/prometheus

  - job_name: webshop_customer_app
    static_configs:
      - targets: [ "http://192.168.0.106:8083" ]
    metrics_path: /actuator/prometheus

  - job_name: webshop_feedback_service
    static_configs:
      - targets: [ "http://192.168.0.106:8182" ]
    metrics_path: /actuator/prometheus

  - job_name: webshop_manager_app
    static_configs:
      - targets: [ "http://192.168.0.106:8080" ]
    metrics_path: /actuator/prometheus