spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/webshop
            user-name-attribute: preferred_username
        registration:
          manager-app:
            client-id: manager-app
            client-secret: kKcwseXqBXKHpQC0dSPAeYSnnBRllPNQ
            provider: keycloak
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt
          metrics:
            provider: keycloak
            client-id: manager-app-metrics-client
            client-secret: sQgXANOQLuCdpvEkMFp6oh0GNoSVVORg
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/webshop
  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:8085
        instance:
          name: manager-app
          service-host-type: ip
  application:
    name: webshop-manager-app
webshop:
  services:
    catalogue:
      uri: http://localhost:8181
      registration-id: manager-app
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'