spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/webshop
            user-name-attribute: preferred_username
        registration:
          manager-app:
            client-id: manager-app
            client-secret: kKcwseXqBXKHpQC0dSPAeYSnnBRllPNQ
            provider: keycloak
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt
          metrics:
            provider: keycloak
            client-id: manager-app-metrics-client
            client-secret: sQgXANOQLuCdpvEkMFp6oh0GNoSVVORg
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
          discovery:
            provider: keycloak
            client-id: manager-app-metrics-client
            client-secret: sQgXANOQLuCdpvEkMFp6oh0GNoSVVORg
            authorization-grant-type: client_credentials
            scope:
              - discovery
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/webshop
  boot:
    admin:
      client:
        enabled: false
webshop:
  services:
    catalogue:
      uri: lb://webshop-catalogue-service
      registration-id: manager-app
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true