server:
  port: 8181
spring:
  application:
    name: webshop-catalogue-service
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://config:password@192.168.0.106:8888