spring:
  security:
    user:
      name: catalogue
      password: password
      roles:
        - ADMIN
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:54321/catalogue
    username: catalogue
    password: catalogue
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  flyway:
    schemas:
      - public
      - catalogue
server:
  port: 8181
logging:
  level:
    sql: info