webshop:
  services:
    catalogue:
      uri: http://localhost:8181
    feedback:
      uri: http://localhost:8182
server:
  port: 8083
spring:
  security:
    oauth2:
      client:
        registration:
#          keycloak:
#            client-id: customer-app
#            client-secret: YOlHt0zDJRQkypI0daqIN0p8Kl6K5EqY
#            scope:
#              - openid
#              - view_catalogue
          customer-app:
            client-id: customer-app
            client-secret: YOlHt0zDJRQkypI0daqIN0p8Kl6K5EqY
            provider: keycloak
            authorization-grant-type: authorization_code
            scope:
              - openid
              - view_catalogue
        provider:
          keycloak:
            issuer-uri: http://localhost://8082/realms/webshop
            user-name-attribute: preferred_username
