webshop:
  services:
    catalogue:
      uri: http://172.30.144.1:8181
    feedback:
      uri: http://172.30.144.1:8182
server:
  port: 8083
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://172.30.144.1:8082/realms/webshop
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: customer-app
            client-secret: YOlHt0zDJRQkypI0daqIN0p8Kl6K5EqY
            scope:
              - openid
              - view_catalogue
          metrics:
            provider: keycloak
            client-id: customer-app-metrics-client
            client-secret: 5o3DqIymzq98yiLNACEiN3UuWuYoQ7jH
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
      resourceserver:
        jwt:
          issuer-uri: http://172.30.144.1:8082/realms/webshop
  boot:
    admin:
      client:
        enabled: true
        url: http://172.30.144.1:8085
        instance:
          name: customer-app
          service-host-type: ip
  application:
    name: webshop-customer-app
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'